In [2]:
import numpy as np
a = np.arange(10)
b = np.arange(15)
a
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [3]:
a = np.arange(15).reshape(3,5)

a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
b = np.array( [11.0, 22.0, 33.0, 44.0] )
print(b)
print(b.dtype)
print(type(b))

[11. 22. 33. 44.]
float64
<class 'numpy.ndarray'>


In [7]:
import numpy as np
c = np.eye(8)
dtype=np.float64
c

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [8]:
d = np.linspace(-1, 2, 15, endpoint=True)
print(d)

[-1.         -0.78571429 -0.57142857 -0.35714286 -0.14285714  0.07142857
  0.28571429  0.5         0.71428571  0.92857143  1.14285714  1.35714286
  1.57142857  1.78571429  2.        ]


In [9]:
e = np.logspace(-1, 2, 15, endpoint=True, base=10)
print(e)

[  0.1          0.16378937   0.26826958   0.43939706   0.71968567
   1.17876863   1.93069773   3.16227766   5.17947468   8.48342898
  13.89495494  22.75845926  37.2759372   61.05402297 100.        ]


In [10]:
f = np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)
f

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [11]:
a = np.arange(12).reshape(3,4)
print(a)
a*2

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [14]:
a = np.arange(12).reshape(3,4)
print(a)
a+a

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [15]:
a = np.arange(12).reshape(3,4)
print(a)
a*a

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [16]:
b = a.transpose()
b

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [17]:
a @ b

array([[ 14,  38,  62],
       [ 38, 126, 214],
       [ 62, 214, 366]])

In [19]:
print(a)
a.sum(axis=1)
a.sum()

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


66

In [20]:
print(a)
a.sum(axis=1)
print(a.min(), a.max())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
0 11


In [22]:
b = a*np.pi/12.0
print(b)
c = np.cos(b)
print(c)
d = b + c 
print(d)

[[0.         0.26179939 0.52359878 0.78539816]
 [1.04719755 1.30899694 1.57079633 1.83259571]
 [2.0943951  2.35619449 2.61799388 2.87979327]]
[[ 1.00000000e+00  9.65925826e-01  8.66025404e-01  7.07106781e-01]
 [ 5.00000000e-01  2.58819045e-01  6.12323400e-17 -2.58819045e-01]
 [-5.00000000e-01 -7.07106781e-01 -8.66025404e-01 -9.65925826e-01]]
[[1.         1.22772521 1.38962418 1.49250494]
 [1.54719755 1.56781598 1.57079633 1.57377667]
 [1.5943951  1.64908771 1.75196847 1.91386744]]


In [23]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [24]:
a = np.arange(12)
a[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [25]:
a = np.arange(12)
a[1:5]

array([1, 2, 3, 4])

In [26]:
for r in a:
    print(r)
a = np.arange(15).reshape(3,5)
print(a)

0
1
2
3
4
5
6
7
8
9
10
11
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [27]:
for e in a.flat:
    print(e)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14


In [28]:
a = np.arange(10)
print(a)
b = a
b.shape = (2, 5)
print(b)
a.shape
print(a)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [29]:
a = np.arange(12)
c = a[:]
a.shape = (3,4)
print(a)
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [30]:
c[1] = -1
print(a)
print(c)

[[ 0 -1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0 -1  2  3  4  5  6  7  8  9 10 11]


In [31]:
d = c[3:8]
print(d)

[3 4 5 6 7]


In [32]:
d[:] = 0 
print(a)
print(c)
print(d)

[[ 0 -1  2  0]
 [ 0  0  0  0]
 [ 8  9 10 11]]
[ 0 -1  2  0  0  0  0  0  8  9 10 11]
[0 0 0 0 0]


In [33]:
print(c is a)
print(c.base is a)
print(c.flags.owndata)
print(a.flags.owndata)

False
True
False
True


In [34]:
d = a.copy()
d[:,:] = 0.0
print(a)
print(d)

[[ 0 -1  2  0]
 [ 0  0  0  0]
 [ 8  9 10 11]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
